FROM node:14

ENV API_URL=https://innbyggerpanelet.dev.intern.nav.no
ENV PORT=3000

WORKDIR /app

COPY . ./

RUN yarn install --production
RUN yarn build:frontend
RUN yarn build:proxy

EXPOSE 3000

CMD node dist/apps/proxy/main.js