FROM node:14.17.0

RUN apt update
RUN wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
RUN apt install ./jdk-17_linux-x64_bin.deb -y

ENV JAVA_HOME /usr/lib/jvm/jdk-17/

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

EXPOSE 8080

CMD ["yarn", "start", "sms"]