FROM node:14

ENV API_URL=https://innbyggerpanelet.dev.intern.nav.no

WORKDIR /app

COPY . ./

RUN yarn install
RUN yarn build

RUN cd apps/frontend/server
RUN yarn build

EXPOSE 3000

CMD node apps/frontend/server/server.js