services:
    app:
        container_name: 'innbyggerpanelet_api'
        build:
            context: .
            dockerfile: Dockerfile.dev
        networks:
            - 'innbyggerpanelet_api'
        ports:
            - 2022:2022
        depends_on:
            - 'db'
        env_file:
            - '.env'
    db:
        container_name: 'innbyggerpanelet_database'
        image: postgres
        volumes:
            - innbyggerpanelet_data:/var/lib/postgresql/data
        networks:
            - innbyggerpanelet_api
        ports:
            - 5432:5432
        env_file:
            - '.env'

volumes:
    innbyggerpanelet_data:
networks:
    innbyggerpanelet_api:
