FROM node:14.17.0

ENV NODE_ENV=development
ENV CLIENT_URL=http://localhost:4200
ENV API_URL=http://localhost:3000
ENV REDIS_HOST=redis

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

EXPOSE 3000

CMD ["yarn", "start", "api"]