version: '3.9'
services:
    web:
        container_name: 'innbyggerpanelet_frontend'
        build:
            context: .
            dockerfile: Dockerfile.frontend.dev
        volumes:
            - './apps/frontend/src:/app/apps/frontend/src'
        networks:
            - innbyggerpanelet_api
        ports:
            - '4200:4200'
        links:
            - 'app:api'
        env_file:
            - '.env'
    app:
        container_name: 'innbyggerpanelet_api'
        build:
            context: .
            dockerfile: Dockerfile.backend.dev
        volumes:
            - ./apps/api/src:/app/apps/api/src
        networks:
            - 'innbyggerpanelet_api'
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}'
        depends_on:
            - 'db'
            - 'redis'
        links:
            - 'redis:redis'
        env_file:
            - '.env'
    db:
        container_name: 'innbyggerpanelet_database'
        image: postgres
        volumes:
            - innbyggerpanelet_data:/var/lib/postgresql/data
        networks:
            - innbyggerpanelet_api
        ports:
            - 5432:5432
        env_file:
            - '.env'
    redis:
        container_name: 'innbyggerpanelet_redis'
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - innbyggerpanelet_api
        ports:
            - 6379:6379
    kafka:
        container_name: 'innbyggerpanelet_kafka'
        image: 'ghcr.io/navikt/tms-event-test-producer/tms-event-test-producer:latest'
        environment:
            - NAIS_NAMESPACE=team-researchops
            - OPEN_INPUT_BESKJED_TOPIC=aapen-brukernotifikasjon-beskjed-v1
            - OPEN_INPUT_OPPGAVE_TOPIC=aapen-brukernotifikasjon-oppgave-v1
            - OPEN_INPUT_INNBOKS_TOPIC=aapen-brukernotifikasjon-innboks-v1
            - OPEN_INPUT_STATUSOPPDATERING_TOPIC=aapen-brukernotifikasjon-statusoppdatering-v1
            - OPEN_INPUT_DONE_TOPIC=aapen-brukernotifikasjon-done-v1
            - KAFKA_BROKERS=tms-event-test-producer
            - KAFKA_SCHEMA_REGISTRY=kafka_schema
            - EVENT_HANDLER_URL=http://localhost:8064
            - EVENTHANDLER_CLIENT_ID=innbyggerpanelet_api
            - CORS_ALLOWED_ORIGINS=*
        networks:
            - innbyggerpanelet_api
        ports:
            - 8064:8064

volumes:
    innbyggerpanelet_data:
networks:
    innbyggerpanelet_api:
