version: '3.9'
services:
    web:
        container_name: 'innbyggerpanelet_frontend'
        build:
            context: .
            dockerfile: Dockerfile.frontend.local
        volumes:
            - './apps/frontend/src:/app/apps/frontend/src'
        networks:
            - innbyggerpanelet_api
        ports:
            - '4200:4200'
        links:
            - 'app:api'
        env_file:
            - '.env'
    app:
        container_name: 'innbyggerpanelet_api'
        build:
            context: .
            dockerfile: Dockerfile.backend.local
        volumes:
            - ./apps/api/src:/app/apps/api/src
        networks:
            - 'innbyggerpanelet_api'
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}'
        depends_on:
            - 'db'
            - 'redis'
        links:
            - 'redis:redis'
        env_file:
            - '.env'
    db:
        container_name: 'innbyggerpanelet_database'
        image: postgres
        volumes:
            - innbyggerpanelet_data:/var/lib/postgresql/data
        networks:
            - innbyggerpanelet_api
        ports:
            - ${INNBYGGERPANELET_DB_PORT}:${INNBYGGERPANELET_DB_PORT}
        environment:
            POSTGRES_DB: ${INNBYGGERPANELET_POSTGRES_DB}
            POSTGRES_USER: ${INNBYGGERPANELET_POSTGRES_USER}
            POSTGRES_PASSWORD: ${INNBYGGERPANELET_POSTGRES_PASSWORD}
            DB_HOST: ${INNBYGGERPANELET_DB_HOST}
            DB_PORT: ${INNBYGGERPANELET_DB_PORT}
        env_file:
            - '.env'
    redis:
        container_name: 'innbyggerpanelet_redis'
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - innbyggerpanelet_api
        ports:
            - 6379:6379

volumes:
    innbyggerpanelet_data:
networks:
    innbyggerpanelet_api:
        external:
          name: dittnav.docker-internal
