FROM node:14

ENV NODE_ENV=production

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn

RUN yarn build api

RUN yarn install --production

EXPOSE 3333

CMD node dist/apps/api/main.js