FROM node:14

ENV IS_PROD=yes
ENV CLIENT_URL=https://innbyggerpanelet.ekstern.dev.nav.no
ENV API_URL=http://innbyggerpanelet-backend
ENV BESKJED_TOPIC=min-side.aapen-brukernotifikasjon-beskjed-v1

WORKDIR /app

COPY . ./

RUN yarn install
RUN yarn build api

EXPOSE 3000

CMD node dist/apps/api/main.js