version: '3.9'
services:
    web:
        container_name: 'innbyggerpanelet_frontend'
        build:
            context: .
            dockerfile: Dockerfile.frontend.dev
        volumes:
            - './apps/frontend/src:/app/src'
        networks:
            - innbyggerpanelet_api
        ports:
            - '4200:4200'
        env_file:
            - '.env'
    app:
        container_name: 'innbyggerpanelet_api'
        build:
            context: .
            dockerfile: Dockerfile.backend.dev
        volumes:
            - ./apps/api/src:/app/scr
        networks:
            - 'innbyggerpanelet_api'
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}'
        depends_on:
            - 'db'
        env_file:
            - '.env'
    db:
        container_name: 'innbyggerpanelet_database'
        image: postgres
        volumes:
            - innbyggerpanelet_data:/var/lib/postgresql/data
        networks:
          - innbyggerpanelet_api
        ports:
            - 5432:5432
        env_file:
          - '.env'
        
volumes:
    innbyggerpanelet_data:
networks:
    innbyggerpanelet_api:
