FROM node:14.17.0

ENV NODE_ENV=development
ENV CLIENT_URL=http://localhost:4200
ENV API_URL=http://localhost:2022

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

EXPOSE 2022

CMD ["yarn", "start", "api"]