apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: innbyggerpanelet-backend
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3000
  team: team-researchops
  liveness:
    path: /isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  env:
    - name: REDIS_HOST
      value: innbyggerpanelet-redis.team-researchops.svc.cluster.local
    - name: IS_PROD
      value: "yes"
    - name: CLIENT_URL
      value: https://innbyggerpanelet.ekstern.dev.nav.no
    - name: API_URL
      value: https://innbyggerpanelet.dev.intern.nav.no
  ingresses:
    - https://innbyggerpanelet.dev.intern.nav.no
  gcp:
    sqlInstances:
      - type: "POSTGRES_12"
        databases:
          - name: "innbyggerpanelet-backend-db"
  azure: 
    application:
      enabled: true

      tenant: nav.no

      replyURLs:
        - "https://innbyggerpanelet.dev.intern.nav.no/azure/oauth2/callback"
        - "http://localhost/api/azure/oauth2/callback"
  kafka:
    pool: nav-dev
  idporten:
    enabled: true
    clientURI: "https://innbyggerpanelet.ekstern.dev.nav.no"
    redirectPath: "https://innbyggerpanelet.ekstern.dev.nav.no/oauth2/callback"
    frontchannelLogoutPath: "https://innbyggerpanelet.ekstern.dev.nav.no/oauth2/logout"
    postLogoutRedirectURIs: 
      - "https://innbyggerpanelet.ekstern.dev.nav.no"

    accessTokenLifetime: 3600
    sessionLifetime: 7200
  accessPolicy:
    inbound:
      rules:
        - application: innbyggerpanelet
    outbound:
      rules: 
        - application: innbyggerpanelet-redis
      