apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: innbyggerpanelet-backend
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3333
  team: team-researchops
  liveness:
    path: /api/isAlive
    port: 3333
    initialDelay: 20
    timeout: 60
  readiness:
    path: /api/isReady
    port: 3333
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: false
    path: /internal/prometheus
  ingresses:
    - https://innbyggerpanelet-backend.dev.intern.nav.no
  gcp:
    sqlInstances:
      - type: "POSTGRES_12"
        databases:
          - name: "innbyggerpanelet-backend-db"