apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: inbyggerpanelet-api
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  iamge: {{ image }}
  port: 3333
  team: team-researchops
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: false
    path: /internal/prometheus
  ingresses:
    - https://innbyggerpanelet-api.dev.intern.nav.no
  gcp:
    sqlInstances:
      - type: "POSTGRES_12"
        databases:
          - name: "innbyggerpanelet-db"