apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: innbyggerpanelet-redis
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
spec:
  image: redis:6.2.6
  team: team-researchops
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: innbyggerpanelet-backend