version: '3.9'
services:
  db:
    container_name: 'innbyggerpanelet_database'
    image: postgres
    volumes:
      - innbyggerpanelet_data:/var/lib/postgresql/data
    ports:
      - ${INNBYGGERPANELET_DB_PORT}:${INNBYGGERPANELET_DB_PORT}
    environment:
      POSTGRES_DB: ${INNBYGGERPANELET_POSTGRES_DB}
      POSTGRES_USER: ${INNBYGGERPANELET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${INNBYGGERPANELET_POSTGRES_PASSWORD}
      DB_HOST: ${INNBYGGERPANELET_DB_HOST}
      DB_PORT: ${INNBYGGERPANELET_DB_PORT}
    env_file:
      - '.env'
volumes:
  innbyggerpanelet_data: