name: Backend CI

on:
  push:
    branches: [main, refactor/workflows-v2]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm install:api
      - name: Build
        run: npm run build api
      - name: Test
        run: npm run test api