name: Deploy citizen

on:
  workflow_dispatch:
  push: 
    branches: [main, dev-**, 170-**]
    #paths: [citizen/**]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}-citizen:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Yarn install
        working-directory: citizen
        run: yarn install
      - name: Yarn build
        working-directory: citizen
        run: yarn build
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: proxy
          file: Dockerfile.web
          push: true
          tags: ${{ env.DOCKER_IMAGE }} 
  
  deploy:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/citizen/dev.yaml
          VAR: image=${{ env.DOCKER_IMAGE }}
