name: Deploy frontend to dev-gcp

on:
    push:
        branches: [main, fix/failing-deploy]

env:
    IMAGE: docker.pkg.github.com/${{ github.repository }}/innbyggerpanelet-frontend:${{ github.sha }}
    CLUSTER: dev-gcp
    RESOURCE: .nais/frontend_dev.yaml

jobs:
    build:
        name: Build and push Docker container
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build and publish Docker image
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn
                  docker build . -t ${IMAGE} -f Dockerfile.frontend.prod
                  docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  docker push ${IMAGE}
    deploy:
        name: Deploy to dev-gcp
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v1
            - name: Deploy to DEV
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY}}
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/frontend_dev.yaml
                  VAR: image=${{ env.IMAGE }}
