name: Deploy backend to dev-gcp

on:
    push:
        branches: [main, dev-**]

env:
    IMAGE: ghcr.io/${{ github.repository }}/innbyggerpanelet-api:${{ github.sha }}
    CLUSTER: dev-gcp
    RESOURCE: .nais/backend_dev.yaml

jobs:
    build:
        name: Build and push Docker container
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build and publish Docker iamge
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  docker build . -t ${IMAGE} -f Dockerfile.backend.dev
                  docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  docker push ${IMAGE}
    deploy:
        name: Deploy to dev-gcp
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v1
            - name: Deploy to DEV
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/backend_dev.yaml,.nais/redis.yaml
                  VAR: image=${{ env.IMAGE }}
