name: Deploy proxy

on:
  workflow_dispatch:
  push:
    branches: [main, dev-**, 170-**]
    #paths: [proxy/**]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}-proxy${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Yarn install
        working-directory: proxy
        run: yarn install
      - name: Yarn build
        working-directory: proxy
        run: yarn build
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./proxy
          push: true
          tags: ${{ env.DOCKER_IMAGE }}