name: Deploy vite-test

on:
  push:
    branches:
      - "main"
      - "dev-**"
      - "170-**"
    paths:
      - "vite-test/**"
env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}-vite-test:$${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./vite-test/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

  deploy:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/vite-test/dev.yaml
          VAR: image=${{ env.DOCKER_IMAGE }}